import '../../models/quiz_models.dart';

/// Sovereign Academic Curriculum Textbook Repository
/// Provides offline, deterministic RAG retrieval of syllabus-aligned questions,
/// verified textbook citations, and pre-seeded live quizzes.
class TextbookQuizRepository {
  /// Standard Academic Textbooks registered in the Campus Repository
  static final List<Map<String, dynamic>> textbooks = [
    {
      "id": "BOOK-ML-GOODFELLOW",
      "title": "Deep Learning & Artificial Neural Networks",
      "author": "Ian Goodfellow, Yoshua Bengio & Aaron Courville",
      "subjectCode": "CS-601",
      "subjectName": "Machine Learning & AI",
      "edition": "1st Edition (MIT Press)",
      "chapters": [
        "Ch 6: Deep Feedforward Networks & Backprop",
        "Ch 7: Regularization & Dropout for Deep Models",
        "Ch 9: Convolutional Neural Networks",
        "Ch 10: Sequence Modeling & Recurrent Nets",
      ],
    },
    {
      "id": "BOOK-OS-GALVIN",
      "title": "Operating System Concepts",
      "author": "Abraham Silberschatz, Peter Galvin & Greg Gagne",
      "subjectCode": "CS-501",
      "subjectName": "Operating Systems",
      "edition": "10th Edition (Wiley)",
      "chapters": [
        "Ch 5: CPU Scheduling & Multiprocessing",
        "Ch 7: Deadlocks & Dijkstra's Banker's Algorithm",
        "Ch 9: Virtual Memory Paging & Replacement",
        "Ch 11: File System Implementation",
      ],
    },
    {
      "id": "BOOK-NET-KUROSE",
      "title": "Computer Networking: A Top-Down Approach",
      "author": "James Kurose & Keith Ross",
      "subjectCode": "CS-602",
      "subjectName": "Computer Networks & Security",
      "edition": "8th Edition (Pearson)",
      "chapters": [
        "Ch 2: Application Layer (HTTP/2, DNS, WebSockets)",
        "Ch 3: Transport Layer (TCP Tahoe/Reno, UDP)",
        "Ch 4: Network Layer (IP Addressing, Routing)",
        "Ch 8: Cryptography & Network Security",
      ],
    },
    {
      "id": "BOOK-COMPILER-DRAGON",
      "title": "Compilers: Principles, Techniques, and Tools",
      "author": "Alfred Aho, Monica Lam, Ravi Sethi & Jeffrey Ullman",
      "subjectCode": "CS-604",
      "subjectName": "Compiler Design & Automata",
      "edition": "2nd Edition (Dragon Book, Pearson)",
      "chapters": [
        "Ch 3: Lexical Analysis & DFA Construction",
        "Ch 4: Syntax Analysis & LR/LALR Parsers",
        "Ch 6: Intermediate Code (Three-Address Code)",
        "Ch 8: Code Generation & Register Allocation",
      ],
    },
    {
      "id": "BOOK-DBMS-KORTH",
      "title": "Database System Concepts",
      "author": "Silberschatz, Henry Korth & S. Sudarshan",
      "subjectCode": "CS-403",
      "subjectName": "Database Management Systems",
      "edition": "7th Edition (McGraw Hill)",
      "chapters": [
        "Ch 7: Relational Database Design & Normalization",
        "Ch 11: Indexing, B+ Trees & Hashing",
        "Ch 14: Transactions & ACID Properties",
        "Ch 15: Concurrency Control (2PL, Timestamping)",
      ],
    },
  ];

  /// Offline Curated Question Banks with Verified Textbook Citations
  static final Map<String, List<QuizQuestion>> textbookQuestionBank = {
    "CS-601": [
      QuizQuestion(
        id: "Q-ML-01",
        questionText: "In reverse-mode automatic differentiation (Backpropagation), how are partial derivatives computed with respect to weights in hidden layers?",
        options: [
          "Direct numerical finite differences perturbation",
          "Applying the multivariate chain rule backwards from loss output",
          "Exclusively using forward-pass gradient accumulation",
          "Randomized Monte Carlo gradient approximations",
        ],
        correctOptionIndex: 1,
        explanation: "Backpropagation applies the multivariate calculus chain rule to recursively compute ∂Loss/∂Weight from the terminal objective layer backward through nested non-linear transformations.",
        textbookCitation: "Ian Goodfellow - Deep Learning, Chapter 6 (Deep Feedforward Networks), Page 204",
        bloomsLevel: BloomsLevel.apply,
      ),
      QuizQuestion(
        id: "Q-ML-02",
        questionText: "What is the primary architectural cause of the Vanishing Gradient problem during backpropagation in deep networks using Sigmoid activation functions?",
        options: [
          "Weights exploding to infinity during matrix multiplication",
          "The maximum derivative of Sigmoid is 0.25, causing exponential gradient decay across deep layers",
          "Learning rate being set excessively high",
          "Insufficient number of training epochs",
        ],
        correctOptionIndex: 1,
        explanation: "Because σ'(z) <= 0.25, multiplying multiple gradients smaller than 1 across deep layers causes the backpropagated error signal to decay exponentially towards zero, stalling weight updates in early layers.",
        textbookCitation: "Ian Goodfellow - Deep Learning, Chapter 6 (Optimization of Deep Models), Page 226",
        bloomsLevel: BloomsLevel.analyze,
      ),
      QuizQuestion(
        id: "Q-ML-03",
        questionText: "How does L1 regularization (Lasso) differ fundamentally from L2 regularization (Ridge) regarding feature weights?",
        options: [
          "L1 encourages exact zero weights, inducing feature sparsity",
          "L2 completely eliminates irrelevant feature coefficients",
          "L1 penalizes squared magnitude of weights",
          "L2 is invariant to linear coordinate scaling",
        ],
        correctOptionIndex: 0,
        explanation: "L1 regularization adds an absolute value penalty (|w|) whose constant gradient drives less significant weights strictly to zero, effectively acting as an automated feature selection mechanism.",
        textbookCitation: "Ian Goodfellow - Deep Learning, Chapter 7 (Regularization for Deep Learning), Page 232",
        bloomsLevel: BloomsLevel.understand,
      ),
      QuizQuestion(
        id: "Q-ML-04",
        questionText: "In Convolutional Neural Networks, a pooling layer with 2x2 filter and stride 2 reduces spatial resolution primarily to achieve which property?",
        options: [
          "Complete inversion invariance",
          "Translation equivariance and spatial dimensionality reduction",
          "Elimination of non-linear activations",
          "Doubling of learnable weight parameters",
        ],
        correctOptionIndex: 1,
        explanation: "Max pooling summarizes neighborhood activations, providing approximate translation invariance while reducing memory footprint and computational complexity in subsequent layers.",
        textbookCitation: "Ian Goodfellow - Deep Learning, Chapter 9 (Convolutional Networks), Page 339",
        bloomsLevel: BloomsLevel.understand,
      ),
      QuizQuestion(
        id: "Q-ML-05",
        questionText: "Which statement regarding the Adam (Adaptive Moment Estimation) optimizer is mathematically TRUE?",
        options: [
          "It uses only zeroth-order gradient information",
          "It maintains running exponentially decaying averages of both past gradients (1st moment) and past squared gradients (2nd moment)",
          "It completely avoids bias correction terms during initial steps",
          "It is identical to standard SGD with constant learning rate",
        ],
        correctOptionIndex: 1,
        explanation: "Adam calculates adaptive learning rates for each parameter by storing an exponentially decaying average of past gradients (m_t) and past squared gradients (v_t), combined with initialization bias correction.",
        textbookCitation: "Ian Goodfellow - Deep Learning, Chapter 8 (Optimization for Training Deep Models), Page 301",
        bloomsLevel: BloomsLevel.analyze,
      ),
    ],

    "CS-602": [
      QuizQuestion(
        id: "Q-NET-01",
        questionText: "In TCP Reno congestion control, what explicit action is taken upon detecting packet loss via a Triple Duplicate ACK?",
        options: [
          "The congestion window (cwnd) is reset to 1 MSS (Slow Start)",
          "The cwnd is halved, ssthresh is set to cwnd/2, and Fast Recovery is entered",
          "The entire connection is terminated with a RST segment",
          "The transmission rate is doubled to overcome queue congestion",
        ],
        correctOptionIndex: 1,
        explanation: "Unlike TCP Tahoe which resets cwnd to 1 MSS, TCP Reno recognizes that 3 duplicate ACKs indicate packets are still traversing the network, so it halves cwnd and triggers Fast Recovery.",
        textbookCitation: "Kurose & Ross - Computer Networking (8th Ed), Chapter 3 (Transport Layer), Page 268",
        bloomsLevel: BloomsLevel.analyze,
      ),
      QuizQuestion(
        id: "Q-NET-02",
        questionText: "What critical limitation of HTTP/1.1 pipelining does HTTP/2 binary framing and stream multiplexing resolve?",
        options: [
          "Inability to transfer HTML text",
          "Head-of-Line (HoL) blocking at the application layer over a single TCP connection",
          "Lack of cryptographic TLS handshake support",
          "Mandatory requirement for 64-bit IP addresses",
        ],
        correctOptionIndex: 1,
        explanation: "HTTP/2 breaks requests and responses into independent binary frames tagged with stream IDs, allowing parallel bidirectional transfers without slow responses blocking subsequent requests.",
        textbookCitation: "Kurose & Ross - Computer Networking (8th Ed), Chapter 2 (Application Layer), Page 134",
        bloomsLevel: BloomsLevel.understand,
      ),
      QuizQuestion(
        id: "Q-NET-03",
        questionText: "The Count-to-Infinity problem is an inherent routing convergence pathology associated with which class of routing algorithms?",
        options: [
          "Link-State (Dijkstra) algorithms",
          "Distance-Vector (Bellman-Ford) routing algorithms",
          "Static centralized routing tables",
          "BGP path vector with loop prevention",
        ],
        correctOptionIndex: 1,
        explanation: "In Distance-Vector routing, good news propagates fast but bad news propagates slowly. A link failure can cause neighboring nodes to update distances cyclically in increments of 1 until infinity.",
        textbookCitation: "Kurose & Ross - Computer Networking (8th Ed), Chapter 4 (The Network Layer), Page 382",
        bloomsLevel: BloomsLevel.apply,
      ),
      QuizQuestion(
        id: "Q-NET-04",
        questionText: "In public-key asymmetric cryptography, if Bob wants to send a confidential encrypted message to Alice, whose key must Bob use to encrypt the payload?",
        options: [
          "Bob's own Private Key",
          "Alice's Public Key",
          "Bob's Public Key",
          "Alice's Private Key",
        ],
        correctOptionIndex: 1,
        explanation: "To ensure confidentiality, the sender encrypts with the recipient's public key (Alice's Public Key). Only Alice possesses the corresponding private key required to decrypt the ciphertext.",
        textbookCitation: "Kurose & Ross - Computer Networking (8th Ed), Chapter 8 (Security in Computer Networks), Page 684",
        bloomsLevel: BloomsLevel.apply,
      ),
    ],

    "CS-604": [
      QuizQuestion(
        id: "Q-CD-01",
        questionText: "In Bottom-Up syntax analysis, what does an LR(1) parser do upon encountering a 'Handle' matching the body of a production rule?",
        options: [
          "It shifts the next input token onto the stack",
          "It reduces the handle by replacing it with the non-terminal head of the production",
          "It emits an immediate syntax error and halts",
          "It restarts the lexical scanner from token zero",
        ],
        correctOptionIndex: 1,
        explanation: "An LR parser operates by shifting tokens until a handle (a substring matching a production right-hand side) is on top of the stack, at which point it reduces it to the non-terminal head.",
        textbookCitation: "Aho, Lam, Sethi, Ullman - Compilers: Principles & Tools (Dragon Book), Chapter 4, Page 241",
        bloomsLevel: BloomsLevel.understand,
      ),
      QuizQuestion(
        id: "Q-CD-02",
        questionText: "Why is Three-Address Code (TAC) widely utilized as an Intermediate Representation (IR) in compiler backends?",
        options: [
          "It directly matches the machine microcode of Intel x86 only",
          "It linearizes complex syntax trees with at most one operator per instruction, simplifying optimization and register allocation",
          "It prevents all lexical errors from occurring",
          "It eliminates the need for symbol tables",
        ],
        correctOptionIndex: 1,
        explanation: "Three-address code decomposes complex nested expressions into a sequence of quadruples or triples with temporary variables (e.g. t1 = a * b; t2 = t1 + c), making instruction scheduling tractable.",
        textbookCitation: "Aho, Lam, Sethi, Ullman - Compilers: Principles & Tools (Dragon Book), Chapter 6, Page 365",
        bloomsLevel: BloomsLevel.analyze,
      ),
      QuizQuestion(
        id: "Q-CD-03",
        questionText: "Which statement correctly distinguishes an SLR(1) parser from a Canonical LR(1) parser?",
        options: [
          "SLR(1) constructs lookahead sets using FOLLOW sets, whereas LR(1) carries lookaheads directly within item states",
          "SLR(1) has more states than Canonical LR(1)",
          "Canonical LR(1) cannot parse unambiguous context-free grammars",
          "SLR(1) is top-down while LR(1) is bottom-up",
        ],
        correctOptionIndex: 0,
        explanation: "SLR(1) reduces on lookahead tokens belonging to FOLLOW(A), which can cause shift-reduce conflicts. Canonical LR(1) resolves this by associating precise lookaheads directly with each grammar item.",
        textbookCitation: "Aho, Lam, Sethi, Ullman - Compilers: Principles & Tools (Dragon Book), Chapter 4, Page 253",
        bloomsLevel: BloomsLevel.analyze,
      ),
    ],

    "CS-501": [
      QuizQuestion(
        id: "Q-OS-01",
        questionText: "In Dijkstra's Banker's Algorithm for deadlock avoidance, what mathematical relation must be satisfied to guarantee that process P_i can safely be granted its request?",
        options: [
          "Request_i <= Need_i AND Request_i <= Available, leaving the system in a verified safe state",
          "Allocation_i + Request_i > Max_i",
          "Available < Request_i",
          "Need_i = Max_i + Allocation_i",
        ],
        correctOptionIndex: 0,
        explanation: "The system verifies that Request <= Need, Request <= Available, and runs the Safety Algorithm ensuring a safe execution sequence exists where all processes can eventually complete.",
        textbookCitation: "Silberschatz & Galvin - Operating System Concepts (10th Ed), Chapter 7 (Deadlocks), Page 328",
        bloomsLevel: BloomsLevel.apply,
      ),
      QuizQuestion(
        id: "Q-OS-02",
        questionText: "What occurs during a Page Fault trap in an operating system implementing virtual memory demand paging?",
        options: [
          "The CPU shuts down due to memory hardware failure",
          "The OS traps to the kernel, swaps the missing page from backing store to a free frame, updates the page table, and restarts the instruction",
          "The entire running process is aborted and removed from the PCB queue",
          "The TLB cache is permanently disabled",
        ],
        correctOptionIndex: 1,
        explanation: "A page fault triggers an OS trap. The kernel locates the required frame on disk, reads it into physical RAM, sets the valid bit in the page table to 1, and restarts the faulted CPU instruction.",
        textbookCitation: "Silberschatz & Galvin - Operating System Concepts (10th Ed), Chapter 9 (Virtual Memory), Page 402",
        bloomsLevel: BloomsLevel.understand,
      ),
    ],
  };

  /// Initial Pre-Seeded Quizzes Active on the Campus
  static List<CampusQuiz> getInitialQuizzes() {
    final now = DateTime.now();
    return [
      CampusQuiz(
        id: "QUIZ-ML-601-01",
        title: "Mid-Term Assessment: Backpropagation & Neural Optimization",
        subjectCode: "CS-601",
        subjectName: "Machine Learning & AI",
        targetBranch: "CSE",
        targetSemester: 6,
        targetYear: 3,
        durationMinutes: 15,
        marksPerQuestion: 4.0,
        hasNegativeMarking: true,
        negativePenalty: 1.0,
        questions: List.from(textbookQuestionBank["CS-601"] ?? []),
        createdByFaculty: "Dr. Mohit Donawat (HOD, CSE)",
        createdAt: now.subtract(const Duration(hours: 2)),
        status: QuizStatus.active,
        totalSubmissions: 38,
        classAverageScore: 14.8,
        highestScore: 20.0,
      ),
      CampusQuiz(
        id: "QUIZ-NET-602-01",
        title: "Class Quiz: Transport Protocols & Congestion Algorithms",
        subjectCode: "CS-602",
        subjectName: "Computer Networks & Security",
        targetBranch: "CSE",
        targetSemester: 6,
        targetYear: 3,
        durationMinutes: 12,
        marksPerQuestion: 2.5,
        hasNegativeMarking: true,
        negativePenalty: 0.5,
        questions: List.from(textbookQuestionBank["CS-602"] ?? []),
        createdByFaculty: "Prof. Priya Verma",
        createdAt: now.subtract(const Duration(days: 1)),
        status: QuizStatus.active,
        totalSubmissions: 41,
        classAverageScore: 7.2,
        highestScore: 10.0,
      ),
      CampusQuiz(
        id: "QUIZ-CD-604-01",
        title: "Automata & Bottom-Up LR Parsing Assessment",
        subjectCode: "CS-604",
        subjectName: "Compiler Design & Automata",
        targetBranch: "CSE",
        targetSemester: 6,
        targetYear: 3,
        durationMinutes: 10,
        marksPerQuestion: 3.0,
        hasNegativeMarking: false,
        negativePenalty: 0.0,
        questions: List.from(textbookQuestionBank["CS-604"] ?? []),
        createdByFaculty: "Dr. S.K. Rathore",
        createdAt: now.subtract(const Duration(days: 3)),
        status: QuizStatus.completed,
        totalSubmissions: 44,
        classAverageScore: 6.8,
        highestScore: 9.0,
      ),
    ];
  }

  /// Initial Real-Time Submissions for the Dynamic Leaderboard
  static List<QuizSubmission> getInitialSubmissions() {
    final now = DateTime.now();
    return [
      QuizSubmission(
        id: "SUB-001",
        quizId: "QUIZ-ML-601-01",
        studentId: "STU-012",
        studentName: "Aman Verma",
        rollNumber: "CS22B012",
        branch: "CSE",
        semester: 6,
        score: 20.0,
        totalPossibleMarks: 20.0,
        correctAnswersCount: 5,
        wrongAnswersCount: 0,
        unansweredCount: 0,
        timeTakenSeconds: 432, // 7m 12s (Fastest)
        submittedAt: now.subtract(const Duration(minutes: 45)),
        selectedAnswers: {0: 1, 1: 1, 2: 0, 3: 1, 4: 1},
      ),
      QuizSubmission(
        id: "SUB-002",
        quizId: "QUIZ-ML-601-01",
        studentId: "STU-034",
        studentName: "Sneha Patel",
        rollNumber: "CS22B034",
        branch: "CSE",
        semester: 6,
        score: 20.0,
        totalPossibleMarks: 20.0,
        correctAnswersCount: 5,
        wrongAnswersCount: 0,
        unansweredCount: 0,
        timeTakenSeconds: 512, // 8m 32s (2nd fastest)
        submittedAt: now.subtract(const Duration(minutes: 38)),
        selectedAnswers: {0: 1, 1: 1, 2: 0, 3: 1, 4: 1},
      ),
      QuizSubmission(
        id: "SUB-003",
        quizId: "QUIZ-ML-601-01",
        studentId: "STU-045",
        studentName: "Rahul Sharma",
        rollNumber: "CS22B045",
        branch: "CSE",
        semester: 6,
        score: 16.0,
        totalPossibleMarks: 20.0,
        correctAnswersCount: 4,
        wrongAnswersCount: 1,
        unansweredCount: 0,
        timeTakenSeconds: 580, // 9m 40s
        submittedAt: now.subtract(const Duration(minutes: 25)),
        selectedAnswers: {0: 1, 1: 1, 2: 0, 3: 0, 4: 1}, // Q3 wrong (-1 penalty)
      ),
      QuizSubmission(
        id: "SUB-004",
        quizId: "QUIZ-ML-601-01",
        studentId: "STU-022",
        studentName: "Pooja Deshmukh",
        rollNumber: "CS22B022",
        branch: "CSE",
        semester: 6,
        score: 15.0,
        totalPossibleMarks: 20.0,
        correctAnswersCount: 4,
        wrongAnswersCount: 1,
        unansweredCount: 0,
        timeTakenSeconds: 645,
        submittedAt: now.subtract(const Duration(minutes: 18)),
        selectedAnswers: {0: 1, 1: 0, 2: 0, 3: 1, 4: 1},
      ),
      QuizSubmission(
        id: "SUB-005",
        quizId: "QUIZ-ML-601-01",
        studentId: "STU-067",
        studentName: "Vikas Meena",
        rollNumber: "CS22B067",
        branch: "CSE",
        semester: 6,
        score: 11.0,
        totalPossibleMarks: 20.0,
        correctAnswersCount: 3,
        wrongAnswersCount: 2,
        unansweredCount: 0,
        timeTakenSeconds: 710,
        submittedAt: now.subtract(const Duration(minutes: 10)),
        selectedAnswers: {0: 1, 1: 0, 2: 1, 3: 1, 4: 1},
      ),
      QuizSubmission(
        id: "SUB-006",
        quizId: "QUIZ-ML-601-01",
        studentId: "STU-089",
        studentName: "Karan Johri",
        rollNumber: "CS22B089",
        branch: "CSE",
        semester: 6,
        score: 7.0,
        totalPossibleMarks: 20.0,
        correctAnswersCount: 2,
        wrongAnswersCount: 3,
        unansweredCount: 0,
        timeTakenSeconds: 830,
        submittedAt: now.subtract(const Duration(minutes: 5)),
        selectedAnswers: {0: 0, 1: 0, 2: 1, 3: 1, 4: 1},
      ),
    ];
  }
}
